version: '3.8'
services:
  app:
    container_name: abc_it
    build: .
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "npm run migrate:run && npm run start:prod"]
  postgres:
    container_name: postgres_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - '5434:${PGPORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
