version: '3.8'
services:
  app:
    container_name: abc_it
    build: .
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    env_file:
      - .env
    depends_on:
      - postgres
    command: ["sh", "-c", "npm run migrate:run"]
  postgres:
    container_name: postgres_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - '${PGPORT}:${PGPORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
